### ISSUE TITLE
Just a single high-pitched note

### ISSUE THREAD

**Issue by Y-Less** [zserge/nokia-composer#2]
Every ringtone I tried was exactly the same - just a single continuous high-pitched note.  No tune at all.

**Comment by zserge** [comment]
Should be fixed in https://github.com/zserge/nokia-composer/commit/cbc3100d6e08e64a9d56014df5159ae57fe7c5ea

**Comment by Y-Less** [comment]
Is that deployed?  Because the live version still has the same issue.

**Comment by zserge** [comment]
@Y-Less I should be deployed automatically, and to me a simple "c d e" line plays with short intervals. Can you try a hard-reload in your browser, perhaps Github Pages still cache the old version?
